###
POST http://localhost:3000/task 
content-type: application/json

{
    "task": "Task 4",
    "email": "task@example.ru",
    "tags":["str","str"]
}

###
GET http://localhost:3000/task


###
GET http://localhost:3000/task/1667193281079

###
GET http://localhost:3000/task/email/task@example.ru

