###
POST http://localhost:3000/task 
content-type: application/json

{
    "task": "Task 4",
    "tags":["str","str"],
    "status": "processing"
}

###
GET http://localhost:3000/task


###
GET http://localhost:3000/task/3